runtime: nodejs20
instance_class: F1

env_variables:
  NODE_ENV: 'production'
  PORT: '3000'
  DB_HOST: 'localhost'
  DB_USER: 'root'
  DB_PASSWORD: '!jeisson'
  DB_NAME: 'sosamet'
  JWT_SECRET: 'key$%'
  SERVER_LOCAL: 'http://localhost:4200'
  SERVER_PROD: 'http://sosametsa.sytes.net'
  EMAIL_USER: 'jedadeveloper32@gmail.com'
  EMAIL_PASS: 'xlil pknq pdav moih'
